##################################################
# Estimate the Parameters of an HMM
#
# http://rosalind.info/problems/BA10H/
# 
# Given: A sequence of emitted symbols x = x1 .
#  . . xn in an alphabet  and a path  = 1 . .
#  . n generated by a k-state HMM with unknown
#  transition and emission probabilities. 
# 
# Return: A matrix of transition probabilities Transition
#  and a matrix of emission probabilities Emission
#  that maximize Pr(x,) over all possible matrices
#  of transition and emission probabilities.
#
# AUTHOR : dohlee
##################################################

# Your imports here


# Your codes here






if __name__ == '__main__':
    # Load the data.
    with open('../../datasets/rosalind_BA10H.txt') as inFile:
        pass

