##################################################
# Implement Viterbi Learning
#
# http://rosalind.info/problems/BA10I/
# 
# Given: A sequence of emitted symbols x = x1 ...
#  xn in an alphabet A, generated by a k-state HMM
#  with unknown transition and emission probabilities,
#  initial Transition and Emission matrices and
#  a number of iterations i.
# 
# Return: A matrix of transition probabilities Transition
#  and a matrix of emission probabilities Emission
#  that maximizes Pr(x, ) over all possible transition
#  and emission matrices and over all hidden paths
#  .  
#
# AUTHOR : dohlee
##################################################

# Your imports here


# Your codes here






if __name__ == '__main__':
    # Load the data.
    with open('../../datasets/rosalind_BA10I.txt') as inFile:
        pass

    # Print output
    with open('../../answers/rosalind_BA10I_out.txt', 'w') as outFile:
        pass
